<?php
if ( function_exists( 'lazyblocks' ) ) :

    lazyblocks()->add_block( array(
        'id' => 213,
        'title' => 'Three columns',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/three-columns',
        'description' => '',
        'category' => 'wightfibre',
        'category_label' => 'wightfibre',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_571a43470a' => array(
                'type' => 'classic_editor',
                'name' => 'content-left',
                'default' => '',
                'label' => 'Content Left',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_7e58204d81' => array(
                'type' => 'classic_editor',
                'name' => 'content-middle',
                'default' => '',
                'label' => 'Content Middle',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_7d6a0946fe' => array(
                'type' => 'classic_editor',
                'name' => 'content-right',
                'default' => '',
                'label' => 'Content Right',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_d3cb1f4223' => array(
                'type' => 'radio',
                'name' => 'vAlign',
                'default' => 'middle',
                'label' => 'Vertical Alignment',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'true',
                'choices' => array(
                    array(
                        'label' => 'Middle',
                        'value' => 'middle',
                    ),
                    array(
                        'label' => 'Top',
                        'value' => 'top',
                    ),
                ),
                'allow_null' => 'false',
                'multiple' => 'false',
                'output_format' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );

endif;